[tool.coverage.html]
directory = "docs/coverage"

[tool.coverage.run]
branch = true
omit = []

[tool.coverage.report]
exclude_lines = [
    "if __name__ == \"__main__\":"
]
fail_under = 80.00
show_missing = true

[tool.coverage.xml]
output = "docs/coverage.xml"

[tool.pytest.ini_options]
addopts = "-rf --verbose --durations=10"
pythonpath = [
    "src"
]
testpaths = [
    "test",
]

